[project]
name = "body-triggered-page-turner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mediapipe>=0.10.32",
    "opencv-python>=4.13.0.92",
    "pyautogui>=0.9.54",
]
